# Generated by Django 4.1.3 on 2022-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewCertificate',
            fields=[
                ('crew_cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('condition', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crew_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('given_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('current_gender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterTownRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_time', models.FloatField(blank=True, null=True)),
                ('trip_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'inter_town_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterTownTrip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inter_town_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalStation',
            fields=[
                ('l_station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_cost', models.FloatField()),
            ],
            options={
                'db_table': 'local_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalTrip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'local_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCertificate',
            fields=[
                ('certificate_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'maintenance_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCrew',
            fields=[
                ('crew_no', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maintenance_crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_cert_id', models.IntegerField()),
                ('task', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTrip',
            fields=[
                ('ticket_trip_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticket_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TownStation',
            fields=[
                ('t_station_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'town_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=1)),
                ('model_number', models.IntegerField()),
                ('max_speed', models.FloatField()),
                ('seats', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('reclining_seats', models.BooleanField()),
                ('luggage_storage', models.BooleanField()),
                ('folding_tables', models.BooleanField()),
                ('vending_machines', models.BooleanField()),
                ('disability_access', models.BooleanField()),
                ('food_services', models.BooleanField()),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
    ]
