# Generated by Django 4.1.3 on 2022-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trip_date',
                'managed': False,
            },
        ),
    ]
